### ISSUE TITLE
Deploying on Heroku

### ISSUE THREAD

**Issue by karneaud** [seybi87/cs-invoice-ninja-source#1]
Hey,

I was researching installing invoice ninja on a heroic account and came across your thread. How were you able to do this? 

Was there anything else needed?

**Comment by seybi87** [comment]
Hi,
I cloned the original source repo of Invoice Ninja and modified it partially (you can check the commit history to check the modifications)
You can deploy this repository without any modifications to Heroku (but a database is currently not configured).
Cheers

**Comment by karneaud** [comment]
@seybi87 thanks but I managed to get something started on bitbucket that will install the latest invoice-ninja on the fly. if you have a bitbucket account I'd be happy to share my code with you in a bid to help make it more efficient

**Comment by karneaud** [comment]
@seybi87 ported it to github https://github.com/karneaud/invoiceninja-buildpack Let me know what you think

**Comment by seybi87** [comment]
Nice work, did the deployment to Heroku work without any custom modifications to the Invoice Ninja source code?

**Comment by karneaud** [comment]
@seybi87 Nope! just incorporate the build pack with the official php build pack and in your project create a custom .env file and it works out of the box( as is).


I am having a personal problem with my project though....I need to integrate a custom plugin for invoice ninja for the project and thus I need to install a private package from bitbucket but it doesn't seem to work. I can't get the build to retrieve the repo via ssh due to authentication reason so I am trying to add the appropriate keys....but I do not know why or have any idea if I am doing.
 it correctly.

I am not familiar with heroku and its build packs or dyno workings....would you be able to assist?

**Comment by seybi87** [comment]
> @seybi87 Nope! just incorporate the build pack with the official php build pack and in your project create a custom .env file and it works out of the box( as is). 

Ok, that's really good!

> I am having a personal problem with my project though....I need to integrate a custom plugin for invoice ninja for the project and thus I need to install a private package from bitbucket but it doesn't seem to work. I can't get the build to retrieve the repo via ssh due to authentication reason so I am trying to add the appropriate keys....but I do not know why or have any idea if I am doing.
it correctly. I am not familiar with heroku and its build packs or dyno workings....would you be able to assist?

Unfortunately not as I am not a Heroku expert. So far I only deployed basic applications to Heroku and didn't include an custom plugins as in your case in Invoice Ninja.

**Comment by karneaud** [comment]
Well if you get a chance again try out my build and let me know your thoughts. Thanks!
